apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "resourse.default.name" . }}
  namespace: {{ .Release.Namespace }}
  labales:
    {{- include "labels.common" . | nindent 4 }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      crd:
        labelSelector: '{{ .Values.Installation.V1.GiantSwarm.FlannelOperator.CRD.LabelSelector }}'
      etcd:
        endpoints: '{{ range $index, $element := .Values.Installation.V1.Provider.KVM.Flannel.EtcdEndpoints }}{{if $index}} {{end}}{{$element}}{{end}}'
        tls:
          cafile: '/etc/kubernetes/ssl/etcd/etcd-ca.pem'
          crtfile: '/etc/kubernetes/ssl/etcd/etcd.pem'
          keyfile: '/etc/kubernetes/ssl/etcd/etcd-key.pem'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
