apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ tpl .Values.resource.default.name . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.selector" . | nindent 8 }}
    spec:
      volumes:
      - name: etcd-certs
        hostPath:
          path: /etc/kubernetes/ssl/etcd/
      - name: {{ tpl .Values.resource.configMap.name . }}
        configMap:
          name: {{ tpl .Values.resource.configMap.name . }}
          items:
            - key: config.yaml
              path: config.yaml
      serviceAccountName: {{ tpl .Values.resource.default.name . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ tpl .Values.resource.default.name . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        volumeMounts:
        - name: {{ tpl .Values.resource.configMap.name . }}
          mountPath: /var/run/flannel-operator/configmap/
        - name: etcd-certs
          mountPath: /etc/kubernetes/ssl/etcd/
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/flannel-operator/configmap/
        - --config.files=config
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 250m
            memory: 200Mi
      imagePullSecrets:
      - name: {{ tpl .Values.resource.pullSecret.name . }}
