apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "resource.pullSecret.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.registry.pullSecret.dockerConfigJSON | quote }}
