apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
spec:
  ports:
  - port: 8000
  selector:
    {{- include "labels.selector" . | nindent 4 }}
