version: 2.1

orbs:
  architect: giantswarm/architect@4.35.5

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build-flannel-operator
          binary: flannel-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build-flannel-operator
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-flannel-operator-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "flannel-operator"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
