flannel:
  etcdEndpoints: []
image:
  name: "giantswarm/flannel-operator"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io
  pullSecret:
    dockerConfigJSON: ""
pod:
  user:
    id: 0
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
