apiVersion: v1
kind: ConfigMap
metadata:
  name: flannel-operator-configmap
  namespace: {{ .Values.namespace }}
data:
  config.yaml: |
    server:
      enable:
        debug:
          server: true
      listen:
        address: 'http://0.0.0.0:8000'
    service:
      crd:
        labelSelector: '{{ .Values.Installation.V1.GiantSwarm.FlannelOperator.CRD.LabelSelector }}'
      etcd:
        endpoints: '{{ .Values.Installation.V1.Provider.KVM.Flannel.EtcdEndpoints }}'
        tls:
          cafile: '/etc/kubernetes/ssl/etcd/etcd-ca.pem'
          crtfile: '/etc/kubernetes/ssl/etcd/etcd.pem'
          keyfile: '/etc/kubernetes/ssl/etcd/etcd-key.pem'
      kubernetes:
        address: ''
        inCluster: true
        tls:
          caFile: ''
          crtFile: ''
          keyFile: ''
