apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        releasetime: {{ $.Release.Time }}
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
      - name: etcd-certs
        hostPath:
          path: /etc/kubernetes/ssl/etcd/
      - name: flannel-operator-configmap
        configMap:
          name: flannel-operator-configmap
          items:
            - key: config.yaml
              path: config.yaml
      serviceAccountName: flannel-operator
      securityContext:
        runAsUser: {{ .Values.userID }}
        runAsGroup: {{ .Values.groupID }}
      containers:
      - name: flannel-operator
        image: quay.io/giantswarm/flannel-operator:[[ .SHA ]]
        volumeMounts:
        - name: flannel-operator-configmap
          mountPath: /var/run/flannel-operator/configmap/
        - name: etcd-certs
          mountPath: /etc/kubernetes/ssl/etcd/
        ports:
        - name: http
          containerPort: 8000
        args:
        - daemon
        - --config.dirs=/var/run/flannel-operator/configmap/
        - --config.files=config
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 250m
            memory: 200Mi
      imagePullSecrets:
      - name: flannel-operator-pull-secret
